### PR TITLE
Revert "Automatic optin to send email alerts for deployment to deployment cre…"

### PR DESCRIPTION
**Pull request by kushalmalani**
Reverts astronomer/houston-api#583

### CODE REVIEW

**Review by vishwas-astro — APPROVED** [review]

**Comment by adam2k** [comment]
Why are these changes being reverted?  Is there a slack convo about it or a GH issue where this was causing problem?

**Review by andriisoldatenko — APPROVED** [review]

**Comment by kushalmalani** [comment]
> Why are these changes being reverted? Is there a slack convo about it or a GH issue where this was causing problem?

https://github.com/astronomer/issues/issues/2217

We just need some more time to get the documentation out for customers, so they are not taken by surprise. We dont want to block the 0.23 release for this

**Comment by adam2k** [comment]
> > Why are these changes being reverted? Is there a slack convo about it or a GH issue where this was causing problem?
> 
> [astronomer/issues#2217](https://github.com/astronomer/issues/issues/2217)
> 
> We just need some more time to get the documentation out for customers, so they are not taken by surprise. We dont want to block the 0.23 release for this

Should we reopen the original issue once this is merged?

**Comment by kushalmalani** [comment]
> > > Why are these changes being reverted? Is there a slack convo about it or a GH issue where this was causing problem?
> > 
> > 
> > [astronomer/issues#2217](https://github.com/astronomer/issues/issues/2217)
> > We just need some more time to get the documentation out for customers, so they are not taken by surprise. We dont want to block the 0.23 release for this
> 
> Should we reopen the original issue once this is merged?

Doing it now

**Pull request merged**
