### PR TITLE
drop old constraint User_localCredential_fkey in User table

### PR DESCRIPTION
**Pull request by andriisoldatenko**
## Description

fix staging database:
```
astronomer_houston=> \d "User";
                         .... some code has been omitted ...
Foreign-key constraints:
    "User_localCredentialId_fkey" FOREIGN KEY ("localCredentialId") REFERENCES "LocalCredential"(id) ON UPDATE CASCADE ON DELETE SET NULL
    "User_localCredential_fkey" FOREIGN KEY ("localCredentialId") REFERENCES "LocalCredential"(id) ON DELETE SET NULL
R
```

### CODE REVIEW

**Comment by adam2k** [comment]
@andriisoldatenko isn't this already implemented in this migration? `src/migrations/20201013142410_update_local_credential_id_fk_reference.js`

**Comment by andriisoldatenko** [comment]
> 20201013142410_update_local_credential_id_fk_reference

nope
20201013142410_update_local_credential_id_fk_referencez

> @andriisoldatenko isn't this already implemented in this migration? `src/migrations/20201013142410_update_local_credential_id_fk_reference.js`

nope we are dropping NEW constraint if exists e.g. recreate. This migration remove old constraint as i demonstrated in description: we should keep new one and drop `"User_localCredential_fkey" FOREIGN KEY `

**Comment by adam2k** [comment]
Ah...nvm, I see.  This migration: `src/migrations/20201013142410_update_local_credential_id_fk_reference.js` is dropping `User_localCredentialId_fkey` and this PR is dropping `User_localCredential_fkey`.

**Review by adam2k — APPROVED** [review]
🎉

**Comment by andriisoldatenko** [comment]
tested locally:
```
postgres=# \d "User";
                                 Table "houston$default.User"
      Column       |              Type              | Collation | Nullable |      Default
-------------------+--------------------------------+-----------+----------+-------------------
 id                | text                           |           | not null |
 username          | text                           |           |          |
 status            | text                           |           |          |
 fullName          | text                           |           |          |
 avatarUrl         | text                           |           |          |
 localCredentialId | text                           |           |          |
 createdAt         | timestamp(3) without time zone |           | not null | CURRENT_TIMESTAMP
 updatedAt         | timestamp(3) without time zone |           | not null |
 token             | text                           |           |          |
 source            | "InviteSource"                 |           |          |
Indexes:
    "User_pkey" PRIMARY KEY, btree (id)
    "User.username_unique" UNIQUE, btree (username)
    "User_localCredentialId_unique" UNIQUE, btree ("localCredentialId")
Foreign-key constraints:
    "User_localCredentialId_fkey" FOREIGN KEY ("localCredentialId") REFERENCES "LocalCredential"(id) ON UPDATE CASCADE ON DELETE SET NULL
```

**Comment by adam2k** [comment]
It looks like the code coverage is dropping because of that log statement in the migration.

**Comment by andriisoldatenko** [comment]
before migration:
```
postgres=# \d "User";
                                 Table "houston$default.User"
      Column       |              Type              | Collation | Nullable |      Default
-------------------+--------------------------------+-----------+----------+-------------------
 id                | text                           |           | not null |
 username          | text                           |           |          |
 status            | text                           |           |          |
 fullName          | text                           |           |          |
 avatarUrl         | text                           |           |          |
 localCredentialId | text                           |           |          |
 createdAt         | timestamp(3) without time zone |           | not null | CURRENT_TIMESTAMP
 updatedAt         | timestamp(3) without time zone |           | not null |
 token             | text                           |           |          |
 source            | "InviteSource"                 |           |          |
Indexes:
    "User_pkey" PRIMARY KEY, btree (id)
    "User.username_unique" UNIQUE, btree (username)
    "User_localCredentialId_unique" UNIQUE, btree ("localCredentialId")
Foreign-key constraints:
    "User_localCredentialId_fkey" FOREIGN KEY ("localCredentialId") REFERENCES "LocalCredential"(id) ON UPDATE CASCADE ON DELETE SET NULL
    "User_localCredential_fkey" FOREIGN KEY ("localCredentialId") REFERENCES "LocalCredential"(id) ON DELETE SET NULL
Referenced by:
    TABLE ""Email"" CONSTRAINT "Email_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"(id) ON UPDATE CASCADE ON DELETE CASCADE
    TABLE ""OAuthCredential"" CONSTRAINT "OAuthCredential_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"(id) ON UPDATE CASCADE ON DELETE CASCADE
    TABLE ""RoleBinding"" CONSTRAINT "RoleBinding_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"(id) ON UPDATE CASCADE ON DELETE CASCADE
```

**Review by kushalmalani — APPROVED** [review]

**Comment by andriisoldatenko** [comment]
> It looks like the code coverage is dropping because of that log statement in the migration.

we have logs in every migration.

**Pull request merged**
