### PR TITLE
Enable Delete and Create Deployment Workers

### PR DESCRIPTION
**Pull request by adam2k**
## Description

Fully enable both create and and delete deployment workers to publish to commander.  Remove commander calls for Create and Delete Deployment Endpoints (there should be a noticeable endpoint response time increase for the end user). 

## 🎟 Issue(s)

Resolves astronomer/issues#1619

## 🧪 Functional Testing

1. In Houston `docker compose up -d`
2. Start Houston API
3. Start Houston Worker
4. Create a kind cluster and inside of commander `make local` - your context should be set via KUBECONFIG via kind
5. Start Astro UI
6. Creating and Deleting Deployment Actions generate the following (look at Houston Worker Logs and look at Commander Logs)

### Creation:

> 📝Note: The worker will receive messages *at least* once.  That means you will see two attempts here on create deployment.

Houston API Worker Logs: 
```
2020-08-14T09:16:58 INFO Created Deployment optical-zenith-8760
2020-08-14T09:17:01 INFO NATS publishing message houston.deployment.created.started for ckdu9a0h3020t0848r8kck9tk.
2020-08-14T09:17:01 INFO Creating database traditional_ecliptic_3191_airflow
2020-08-14T09:17:01 INFO Created airflow schema for traditional_ecliptic_3191_airflow
2020-08-14T09:17:01 INFO Created celery schema for traditional_ecliptic_3191_celery
2020-08-14T09:17:01 INFO Created database traditional_ecliptic_3191_airflow
2020-08-14T09:17:01 INFO Final helm values:
...
2020-08-14T09:17:01 INFO Calling commander method #createDeployment
2020-08-14T09:17:31 INFO NATS publishing message houston.deployment.created.started for ckdu9a0h3020t0848r8kck9tk.
2020-08-14T09:17:31 INFO Creating database traditional_ecliptic_3191_airflow
2020-08-14T09:17:31 INFO Created airflow schema for traditional_ecliptic_3191_airflow
2020-08-14T09:17:31 INFO Created celery schema for traditional_ecliptic_3191_celery
2020-08-14T09:17:31 INFO Created database traditional_ecliptic_3191_airflow
2020-08-14T09:17:31 INFO Final helm values:
```

Commander logs (Local Development):
```
IINFO[0363] releaseName traditional-ecliptic-3191, chart astronomer-ee/airflow, chartVersion 0.16.2, namespace datarouter-dev-traditional-ecliptic-3191  function=InstallRelease package=helm
INFO[0364] CHART PATH: /Users/adamvandover/Library/Caches/helm/repository/airflow-0.16.2.tgz  function=InstallRelease package=helm
INFO[0392] releaseName traditional-ecliptic-3191, chart astronomer-ee/airflow, chartVersion 0.16.2, namespace datarouter-dev-traditional-ecliptic-3191  function=InstallRelease package=helm
INFO[0393] CHART PATH: /Users/adamvandover/Library/Caches/helm/repository/airflow-0.16.2.tgz  function=InstallRelease package=helm
ERRO[0393] cannot re-use a name that is still in use     function=InstallDeployment package=kubernetes
```

### Deletion:

> 📝Note: The worker will receive messages *at least* once as they come in, so by creating and deleting a deployment back to back the logs are out of order to when the user action occurs.

Houston Worker Logs: 
```
2020-08-14T09:20:21 INFO Calling commander method #deleteDeployment
2020-08-14T09:20:23 INFO Response from #deleteDeployment: {"result":{"success":true,"message":"Deployment Deleted"},"deployment":{"releaseName":"traditional-ecliptic-3191"}}
2020-08-14T09:20:23 INFO Deployment traditional-ecliptic-3191 successfully deleted
2020-08-14T09:20:29 INFO Response from #createDeployment: {"result":{"success":true,"message":"Deployment Created"},"deployment":{"releaseName":"traditional-ecliptic-3191"}}
2020-08-14T09:20:29 INFO Created Deployment traditional-ecliptic-3191
```

Commander Logs:
```
DEBU[0563] helm#DeleteRelease                            function=DeleteRelease package=helm
INFO[0565] release "traditional-ecliptic-3191" uninstalled  function=DeleteRelease package=helm
```

## 📸 Screenshots

No UI changes for this PR.  All the changes are contained within the logs above.

## 📋 Checklist

- [x] Rebased from the main (or release if patching) branch (before testing)
- [x] Ran `yarn lint && yarn test` before taking out of draft
- [x] Added/updated applicable tests
- [x] Tested against [Astro-UI](https://github.com/astronomer/astro-ui/) and [Astro-CLI](https://github.com/astronomer/astro-cli/) clients.
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/astro-docs/)

### CODE REVIEW

**Comment by adam2k** [comment]
I'm going to take this out of Draft.  I'm looking into that drop in code coverage to see what I can do.  That's all I plan on updating beyond what's in there now.

**Comment by adam2k** [comment]
@schnie @andriisoldatenko when you go through this can you take a look at the logs that I put into the PR comment.  Specifically the Commander logs.  I want to make sure that the failed "createDeployment" the second time around (re-ack() messages) won't have a major negative impact on the system.

**Comment by schnie** [comment]
@adam2k how does that create/delete cycle work? So you created a deployment, then quickly deleted it and the operations happened out of order? What happened there?

**Comment by adam2k** [comment]
> @adam2k how does that create/delete cycle work? So you created a deployment, then quickly deleted it and the operations happened out of order? What happened there?

The short answer is, deleting a deployment while the create action of the same deployment is still running will delete the k8s deployment and return a success message back for both delete and create.

For Info:

Testing locally using a empty kind cluster and commander, I can start the process of creating a deployment, but the pods stay in a "pending" state.  As soon as I send the delete request, the pods are correctly deleted and at that point I'll receive a success response back in the worker from commander about the "Created Deployment."  If I don't delete the pods the create deployment will hang and I'll eventually receive a failure timeout message.  This isn't something that would happen in staging or prod.

You can see my current local k8s state.  I don't see the `traditional-ecliptic-3191` pods anywhere after the actions in the logs returned out of order `delete` then `created`.

```NAMESPACE                               NAME                                                   READY   STATUS                  RESTARTS   AGE
datarouter-dev-ecliptical-corona-2547   ecliptical-corona-2547-create-user-s97lv               0/1     Pending                 0          2d23h
datarouter-dev-ecliptical-corona-2547   ecliptical-corona-2547-flower-5cd8fc474b-fjfs9         0/1     Pending                 0          2d23h
datarouter-dev-ecliptical-corona-2547   ecliptical-corona-2547-pgbouncer-ffcfdb498-g9ts8       0/2     Pending                 0          2d23h
datarouter-dev-ecliptical-corona-2547   ecliptical-corona-2547-redis-0                         0/1     Pending                 0          2d23h
datarouter-dev-ecliptical-corona-2547   ecliptical-corona-2547-scheduler-6cc987c57-c8pfd       0/2     Pending                 0          2d23h
datarouter-dev-ecliptical-corona-2547   ecliptical-corona-2547-statsd-7975f9997-kr4vp          0/1     Pending                 0          2d23h
datarouter-dev-ecliptical-corona-2547   ecliptical-corona-2547-webserver-5687d9949b-ndxsw      0/1     Pending                 0          2d23h
datarouter-dev-ecliptical-corona-2547   ecliptical-corona-2547-worker-0                        0/2     Pending                 0          2d23h
datarouter-dev-empty-nova-1314          empty-nova-1314-create-user-stxm4                      0/1     ImagePullBackOff        0          3d
datarouter-dev-empty-nova-1314          empty-nova-1314-flower-5865f48cf4-qn9q9                0/1     ImagePullBackOff        0          3d
datarouter-dev-empty-nova-1314          empty-nova-1314-pgbouncer-bdff984fd-wwnpv              2/2     Running                 0          3d
datarouter-dev-empty-nova-1314          empty-nova-1314-redis-0                                1/1     Running                 0          3d
datarouter-dev-empty-nova-1314          empty-nova-1314-scheduler-64ff464469-9m9sh             0/2     Pending                 0          3d
datarouter-dev-empty-nova-1314          empty-nova-1314-statsd-9bcc5b65c-f48x9                 1/1     Running                 0          3d
datarouter-dev-empty-nova-1314          empty-nova-1314-webserver-6f8d9cff4b-hls4w             0/1     Init:ImagePullBackOff   0          3d
datarouter-dev-empty-nova-1314          empty-nova-1314-worker-0                               0/2     Pending                 0          3d
datarouter-dev-weightless-cosmic-3034   weightless-cosmic-3034-create-user-fgt97               0/1     Pending                 0          3d
datarouter-dev-weightless-cosmic-3034   weightless-cosmic-3034-flower-7c55df647c-rb8jq         0/1     Pending                 0          3d
datarouter-dev-weightless-cosmic-3034   weightless-cosmic-3034-pgbouncer-6c8f5846b5-7g24v      0/2     Pending                 0          3d
datarouter-dev-weightless-cosmic-3034   weightless-cosmic-3034-redis-0                         0/1     Pending                 0          3d
datarouter-dev-weightless-cosmic-3034   weightless-cosmic-3034-scheduler-c9656c654-56pxd       0/2     Pending                 0          3d
datarouter-dev-weightless-cosmic-3034   weightless-cosmic-3034-statsd-67994d9b84-prgwd         0/1     Pending                 0          3d
datarouter-dev-weightless-cosmic-3034   weightless-cosmic-3034-webserver-6f79cf94c5-db2vp      0/1     Pending                 0          3d
datarouter-dev-weightless-cosmic-3034   weightless-cosmic-3034-worker-0                        0/2     Pending                 0          3d
kube-system                             coredns-66bff467f8-gsbld                               1/1     Running                 0          3d15h
kube-system                             coredns-66bff467f8-smzm6                               1/1     Running                 0          3d15h
kube-system                             etcd-commander-kind-control-plane                      1/1     Running                 0          3d15h
kube-system                             kindnet-b4gpl                                          1/1     Running                 0          3d15h
kube-system                             kube-apiserver-commander-kind-control-plane            1/1     Running                 0          3d15h
kube-system                             kube-controller-manager-commander-kind-control-plane   1/1     Running                 2          3d15h
kube-system                             kube-proxy-rbnxj                                       1/1     Running                 0          3d15h
kube-system                             kube-scheduler-commander-kind-control-plane            1/1     Running                 2          3d15h
local-path-storage                      local-path-provisioner-bd4bb6b75-mr9wh                 1/1     Running                 0          3d15h
```

**Comment by adam2k** [comment]
@schnie one use case that I am thinking about right now is when the worker stops and comes back up (re-subscribes), the NATS Streaming server will send out all of the messages that it has for that particular subscription.  Right now, that'll re-send all of the commander calls.  This should still keep the cluster in the correct state, but it will make for an unnecessary increase in commander calls during that initial restart period.  I will probably need to create a new issue to investigate this further.

**Comment by schnie** [comment]
We _could_ make commander a sidecar to the Houston worker pods in the future to help out there

**Pull request merged**
