### PR TITLE
Fix/nats logs houston wait

### PR DESCRIPTION
**Pull request by adam2k**
## Description

Remove unneeded cluster logs (always prints {envname}-stan)
Change how we are waiting for NATS to come up with the new `NATS__SERVERS` env var.

## 🎟 Issue(s)

Resolves astronomer/issues#XXXX

## 🧪 Functional Testing

Double check that the log format looks correct.

For the NATS Server env var the easiest way to test is to run the script locally in terminal:

```
$ echo '["localhost:4222","localhost:5222"]' | awk -F\" 'NF>=3 {print $2}' | awk -F: '{print $1}'
localhost
$ echo '["localhost:4222","localhost:5222"]' | awk -F\" 'NF>=3 {print $2}' | awk -F: '{print $2}'
4222
```

## 📸 Screenshots

N/A

## 📋 Checklist

- [x] Rebased from the main (or release if patching) branch (before testing)
- [x] Ran `yarn lint && yarn test` before taking out of draft
- [ ] Added/updated applicable tests
- [ ] Tested against [Astro-UI](https://github.com/astronomer/astro-ui/) and [Astro-CLI](https://github.com/astronomer/astro-cli/) clients.
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/astro-docs/)

### CODE REVIEW

**Review by andriisoldatenko — APPROVED** [review]
practically LGTM
```
NAME                                                       READY   STATUS      RESTARTS   AGE
astronomer-astro-ui-84c69f4c58-gr7xz                       1/1     Running     0          4m57s
astronomer-cli-install-568596b594-cwh2l                    1/1     Running     0          4m56s
astronomer-commander-6b5488f977-lmzf7                      1/1     Running     0          4m58s
astronomer-houston-655cbf85bf-kv26v                        1/1     Running     0          4m58s
astronomer-houston-upgrade-deployments-kndw7               0/1     Completed   0          4m57s
astronomer-houston-worker-757cb89cf9-kgr8l                 1/1     Running     0          4m58s
astronomer-houston-worker-757cb89cf9-wjffh                 1/1     Running     0          4m58s
astronomer-kubed-6cc48c5767-9g6fg                          1/1     Running     0          4m58s
astronomer-nats-0                                          2/2     Running     0          4m57s
astronomer-nats-1                                          2/2     Running     0          2m24s
astronomer-nats-2                                          2/2     Running     0          2m9s
astronomer-nginx-57c6dd66d7-xnndc                          1/1     Running     0          4m58s
astronomer-nginx-default-backend-855c4dff86-ls5w9          1/1     Running     0          4m57s
astronomer-postgresql-0                                    1/1     Running     0          4m57s
astronomer-prisma-857648755b-f7kgc                         1/1     Running     0          4m58s
astronomer-prometheus-blackbox-exporter-65f6c5f456-944kx   1/1     Running     0          4m57s
astronomer-prometheus-blackbox-exporter-65f6c5f456-qqj6f   1/1     Running     0          4m57s
astronomer-registry-0                                      1/1     Running     0          4m57s
astronomer-stan-0                                          2/2     Running     0          4m57s
astronomer-stan-1                                          2/2     Running     0          2m2s
astronomer-stan-2  
```

**Comment by adam2k** [comment]
Do we need to hold on merging until the charts are updated?

**Comment by andriisoldatenko** [comment]
we need to merge to fix CI/CD here -> https://github.com/astronomer/astronomer/pull/824/files#diff-252d098af651bc3cec78dcadc46dc053

**Comment by andriisoldatenko** [comment]
@adam2k pls merge this.

**Pull request merged**
