### PR TITLE
Hotfix: 1986 Exclude deleted deployments

### PR DESCRIPTION
**Pull request by samblackk**
## Description

Hotfix issue of deleted deployment being accessible in the UI because it's still returning from the API.

## 🎟 Issue(s)

Resolves https://github.com/astronomer/issues/issues/1986

## 🧪 Functional Testing

1. Start Houston API
2. Create a deployment 
3. Let the deployment spin up completely 
4. Delete deployment 
5. Query `workspace-deployment` 
6. Get empty response

## 📸 Screenshots

N/A

## 📋 Checklist

- [x] Rebased from the main (or release if patching) branch (before testing)
- [x] Ran `yarn lint && yarn test` before taking out of draft
- [x] Added/updated applicable tests
- [x] Tested against [Astro-UI](https://github.com/astronomer/astro-ui/) and [Astro-CLI](https://github.com/astronomer/astro-cli/) clients.
- [x] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [x] Updated any related [documentation](https://github.com/astronomer/docs/)

### CODE REVIEW

**Comment by kushalmalani** [comment]
Can we add a unit tests for this? also, do we need similar change for the query workspaceDeployments?

**Review by schnie — APPROVED** [review]

**Comment by andriisoldatenko** [comment]
@kushalmalani it's already there https://github.com/astronomer/houston-api/blob/3300c9e743e1b340e80ccde2aa7b11568caf0124/src/resolvers/query/workspace-deployments/index.js#L54

unit test nice to have, can you please help @samblackk  how we check such changes.

**Comment by kushalmalani** [comment]
> @kushalmalani it's already there
> 
> https://github.com/astronomer/houston-api/blob/3300c9e743e1b340e80ccde2aa7b11568caf0124/src/resolvers/query/workspace-deployments/index.js#L54
> 
> unit test nice to have, can you please help @samblackk how we check such changes.
> 
> e.g. `toHaveBeenCalledWith({});` would be enough.

@samblackk You can add something like this

`expect(prisma.deployment.findOne).toHaveBeenCalledWith({
      where: { deletedAt: null, releaseName: vars.releaseName }
    })`

**Comment by kushalmalani** [comment]
@samblackk Did we validate this? I was trying something similar else where and my mutation fails on similar query

**Comment by samblackk** [comment]
@adam2k @kushalmalani @andriisoldatenko Test is updated, branch is rebased

**Review by kushalmalani — APPROVED** [review]

**Review by andriisoldatenko — APPROVED** [review]

**Pull request merged**
