### PR TITLE
Fix redirect for old style wildcard Airflow URLs

### PR DESCRIPTION
**Pull request by ashb**
This is generating this config snippet in 
```
                location ^~ /api/ {
                        if ($host = 'deployments.staging.astronomer.io' ) {
                                return 404;
                        }
                        proxy_pass https://deployments.staging.astronomer.io/airflow/$request_uri;
                }
```

It should have been

```
                     location ^~ /api/ {
                       if ($host = 'deployments.staging.astronomer.io' ) {
                         return 404;
                       }
                       proxy_pass https://deployments.staging.astronomer.io/planetoidal-telescope-7313/airflow/$request_uri;
                     }
```

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
it's interesting i did similar change... anyway LGTM

**Comment by andriisoldatenko** [comment]
@ashb linters...

**Comment by ashb** [comment]
Ugh "prettier" wants to make it uglier:

```
/root/project/src/lib/deployments/config/index.js
 
  104:49  error  Replace `deployment.releaseName` with `⏎············deployment.releaseName⏎··········`  prettier/prettier
 
  108:49  error  Replace `deployment.releaseName` with `⏎············deployment.releaseName⏎··········`  prettier/prettier
 
  118:48  error  Replace `deployment.releaseName` with `⏎············deployment.releaseName⏎··········`  prettier/prettier
 

 
```

**Comment by andriisoldatenko** [comment]
i fixed trivy in master, but for release branch we can skip.

**Pull request merged**
