### PR TITLE
Fix: deployment name validation

### PR DESCRIPTION
**Pull request by samblackk**
Fix https://github.com/astronomer/issues/issues/1364

Updates validation check for manual `releaseName` during auth validation. 

Plz review.

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@samblackk LGTM, can we add/or update tests?

**Comment by samblackk** [comment]
src/lib/deployments/logs/index.js | 78.57% <0.00%> (-7.15%)
-- | --

Is caused by changes not made on this branch. We can merge and fix the effected `logs/index` tests later.

**Comment by vishwas-astro** [comment]
> src/lib/deployments/logs/index.js	78.57% <0.00%> (-7.15%)
> Is not caused by changes not made on this branch. We can merge and fix `logs/index` tests later.

Yeah, lets merge for now.

**Comment by andriisoldatenko** [comment]
@samblackk i rebased from master.

**Comment by andriisoldatenko** [comment]
@schnie are we good to go?

**Pull request merged**
