### PR TITLE
Return back ingress class

### PR DESCRIPTION
**Pull request by andriisoldatenko**

### CODE REVIEW

**Comment by sjmiller609** [comment]
@andriisoldatenko is it possible to push an image you built locally to some arbitrary dockerhub org where we can edit in dev cluster to validate that it works before we merge?

**Comment by andriisoldatenko** [comment]
yep.

**Comment by andriisoldatenko** [comment]
@schnie can you please merge this?

**Comment by sjmiller609** [comment]
gonna discuss the merge to master stuff

**Pull request merged**
