### PR TITLE
Remove legacy uuid aliases from schema

### PR DESCRIPTION
**Pull request by ryanahamilton**
These are no longer needed by our clients.

Removes aliases from Astro UI in: astronomer/astro-ui#608

Removes aliases from Astro CLI in: astronomer/astro-cli#336

bump apollo server to fix security issues.

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@ryanahamilton thank you!

**Comment by andriisoldatenko** [comment]
pls rebase from master to fix trivy!

**Comment by ryanahamilton** [comment]
@andriisoldatenko branch is already up-to-date w/ master

**Comment by schnie** [comment]
Awesome, thanks! Can also remove the `@alias` directive code itself. We made this thing so should be under `src/lib/directives/alias`.

**Comment by ryanahamilton** [comment]
@schnie we still have 3 instances of `@alias` being used on other fields in the schema. In trying to keep the scope of this simple, I didn't look into the feasibility of removing those as well. Better suited in a follow-up PR?

**Comment by andriisoldatenko** [comment]
LGTM.

**Comment by andriisoldatenko** [comment]
@schnie good to merge?

**Pull request merged**
