### PR TITLE
desctroy explicitly knex connection pool

### PR DESCRIPTION
**Pull request by andriisoldatenko**
fix https://github.com/astronomer/issues/issues/660

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@schnie similar to https://github.com/astronomer/houston-api/blob/ae9d17939c3865c2d02b666ed0261536159bd3a0/src/lib/deployments/database/index.js#L140-L142

**Comment by samblackk** [comment]
The rare time that `async` fails to be useful.

**Comment by andriisoldatenko** [comment]
```
postgres-# \l
                                          List of databases
             Name             |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
------------------------------+----------+----------+------------+------------+-----------------------
 postgres                     | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 sidereal_vacuum_8961_airflow | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0                    | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
                              |          |          |            |            | postgres=CTc/postgres
 template1                    | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
                              |          |          |            |            | postgres=CTc/postgres
(4 rows)
```

```
$ houston-api git:(houston-cleanup-job-hanging) ✗ npx babel-node src/scripts/cleanup-deployments/index.js
2019-12-13T20:13:15 INFO Starting registry cleanup
2019-12-13T20:13:15 INFO There are no deployments to delete
2019-12-13T20:13:15 INFO removeDatabaseForDeployment
2019-12-13T20:13:15 INFO Dropping database: sidereal_vacuum_8961_airflow
```

after:
```
postgres-# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(3 rows)
```

**Comment by andriisoldatenko** [comment]
@ashb @schnie PTAL
practically LGTM
i have deployed 3 new deployments:
```
postgres=# select "releaseName", "deletedAt" from "houston$default"."Deployment";
         releaseName         | deletedAt
-----------------------------+-----------
 meteoroidal-diameter-6992   |
 arithmetic-transit-7891     |
 geostationary-asterism-7463 |
(3 rows)
```

Expire deployments:
```
postgres=# update "houston$default"."Deployment" set "deletedAt" = (NOW() - interval '1 month');
UPDATE 3
```

run cleanup:
```
npx babel-node src/scripts/cleanup-deployments/index.js
➜  houston-api git:(houston-cleanup-job-hanging) ✗ npx babel-node src/scripts/cleanup-deployments/index.js
2019-12-16T14:44:18 INFO Starting registry cleanup
2019-12-16T14:44:18 INFO Dropping database: meteoroidal_diameter_6992_airflow
2019-12-16T14:44:18 DEBUG Requesting docker tags for meteoroidal-diameter-6992 at http://deadly-terrier-registry.datarouter:5000/v2/meteoroidal-diameter-6992/airflow/tags/list
(node:64054) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2019-12-16T14:44:18 ERROR Error: getaddrinfo ENOTFOUND deadly-terrier-registry.datarouter
2019-12-16T14:44:18 INFO There is no tags to delete
2019-12-16T14:44:18 INFO Dropping database: arithmetic_transit_7891_airflow
2019-12-16T14:44:18 DEBUG Requesting docker tags for arithmetic-transit-7891 at http://deadly-terrier-registry.datarouter:5000/v2/arithmetic-transit-7891/airflow/tags/list
2019-12-16T14:44:18 ERROR Error: getaddrinfo ENOTFOUND deadly-terrier-registry.datarouter
2019-12-16T14:44:18 INFO There is no tags to delete
2019-12-16T14:44:18 INFO Dropping database: geostationary_asterism_7463_airflow
2019-12-16T14:44:18 DEBUG Requesting docker tags for geostationary-asterism-7463 at http://deadly-terrier-registry.datarouter:5000/v2/geostationary-asterism-7463/airflow/tags/list
2019-12-16T14:44:18 ERROR Error: getaddrinfo ENOTFOUND deadly-terrier-registry.datarouter
2019-12-16T14:44:18 INFO There is no tags to delete
```

Check database:
```
postgres=# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(3 rows)
```

Check deployments:

```
postgres=# select "releaseName", "deletedAt" from "houston$default"."Deployment";
 releaseName | deletedAt
-------------+-----------
(0 rows)
```

**Pull request merged**
