### PR TITLE
Card Mutation & Query: Add fallback for company

### PR DESCRIPTION
**Pull request by samblackk**
Fix https://github.com/astronomer/astro-ui/issues/306

There is a bug where there isn't a fallback for adding the `company` field properly during `addCard()` mutations. This fixes that up and allows backwards compatibility. 

Ready for merge.

### CODE REVIEW

**Comment by ryanahamilton** [comment]
@schnie mind reviewing/merging this one?

**Comment by schnie** [comment]
@samblackk @ryanahamilton what exactly happened that requires this change?

**Comment by samblackk** [comment]
@schnie In current orbit we got around this by sending the fallback from Orbit. In `astro-ui` we're not sending the fallback as it should happen in Houston.

**Comment by schnie** [comment]
@samblackk so this is to make Houston work for Orbit and Astro UI, but after Orbit is dead, we can just use the new path?

**Comment by samblackk** [comment]
Yep!

**Comment by schnie** [comment]
Since we're moving forward with Astro UI, I'm wondering if we should just support Astro UI here, since they'll ship together.

**Comment by ryanahamilton** [comment]
@schnie this update _is_ what is needed in order to support Astro UI. It just doesn't break with the current Orbit because this additional fallback logic is handled by the client, but should be moved (by this PR) to the the API. We aren't going out of the way to support the old Orbit in any way.

**Pull request merged**
