### PR TITLE
Remove unnecessary deploymentCount field

### PR DESCRIPTION
**Pull request by ryanahamilton**
Requires astronomer/astro-ui#547 merged first.

Trimming some fat by removing this field that is redundant with the existing `deployments` field. The aforementioned Astro UI PR illustrates the client execution.

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@ryanahamilton 

```
root/project/src/resolvers/types/workspace/index.js 
  5:26  error  'size' is defined but never used  no-unused-vars
 
✖ 1 problem (1 error, 0 warnings)
```

**Comment by andriisoldatenko** [comment]
@schnie we need also remove it from astro-cli 
https://github.com/astronomer/astro-cli/blob/bb4da75e37f44ce75f1ff7ac5eb34f0cd3800819/houston/queries.go#L342

**Comment by schnie** [comment]
@andriisoldatenko can you clean that up in the CLI?

**Comment by ryanahamilton** [comment]
UI dependency has been merged, and I've opened a [CLI PR](https://github.com/astronomer/astro-cli/pull/333) to clean up the reference there.

**Pull request merged**
