### PR TITLE
add special case for Airflow 1.10.5

### PR DESCRIPTION
**Pull request by andriisoldatenko**
based on message in slack
@schnie wrote:
>Repeating back what I'm reading here -
We need to add special logic to Houston, so that if a user pushes a 1.10.5-based image up, we continue to run the 1.10.7 initContainers. Otherwise run the exactly matching version of the initContainer.

### CODE REVIEW

**Comment by sjmiller609** [comment]
hey, you beat me to it. what's the difference between this change and this one: https://github.com/astronomer/houston-api/commit/3d1374d3f91905871d3db430d432f55cf09afb85

**Comment by sjmiller609** [comment]
I think yours changes the database to have version 1.10.7 for label 1.10.5, is that right?

**Comment by ashb** [comment]
> I think yours changes the database to have version 1.10.7 for label 1.10.5, is that right?

Yup.

**Comment by sjmiller609** [comment]
also I think we want to modify config/test.yaml to have for image list: https://github.com/astronomer/google-environments/blob/7c502e22bde2c19ebfd760b82b7ef66a56c01e74/config.yaml#L149-L222

**Comment by andriisoldatenko** [comment]
@ashb i'm not sure if it's a good idea or not.... it can confuse in database 
1.10.5 and in reality it's 1.10.7 isn't?

**Comment by andriisoldatenko** [comment]
as confirmed in slack, we should change only helm values, and keep Deployment record in DB as is.

**Comment by andriisoldatenko** [comment]
practically LGTM did tests in staging:
i created new deployment:
```
kubectl describe pod primitive-eccentricity-6872-scheduler-5b46d66894-dzq4g  -n astronomer-primitive-eccentricity-6872 | grep -i Image
    Image:         astronomerinc/ap-airflow:1.10.7-alpine3.10-onbuild
    Image ID:      docker-pullable://astronomerinc/ap-airflow@sha256:47b1d09d9e677c1f3bccb0c187edca88c76501b9f0c77e3a1fe35efd590a7335
    Image:         docker.io/istio/proxyv2:1.4.3
    Image ID:
    Image:         astronomerinc/ap-airflow:1.10.7-alpine3.10-onbuild
    Image ID:
    Image:         astronomerinc/ap-airflow:1.10.7-alpine3.10-onbuild
    Image ID:
    Image:         docker.io/istio/proxyv2:1.4.3
    Image ID:
  Normal   Pulled       43s   kubelet, gke-staging-cluster-staging-mt-01-08--8d39ee60-lcq0  Container image "astronomerinc/ap-airflow:1.10.7-alpine3.10-onbuild" already present on machine
```

than i deployed using `astro deploy`:
```
cat Dockerfile
FROM astronomerinc/ap-airflow:1.10.5-alpine3.10-onbuild
```

and now i see:
```
Controlled By:  ReplicaSet/primitive-eccentricity-6872-scheduler-8555bc8644
Init Containers:
  run-airflow-migrations:
    Container ID:  docker://0024c3f0117a6920126286f49c83647459b9e041013ff100c88a66bbcd90bb41
    Image:         astronomerinc/ap-airflow:1.10.7-alpine3.10-onbuild
```

**Pull request merged**
