### PR TITLE
Create wrapper for publisher error handling

### PR DESCRIPTION
**Pull request by adam2k**
## Description

This PR adds an extra layer of abstraction between NATS Streaming and our publishers so we can more effectively error handle for our use case. 

## 🎟 Issue(s)

Resolves astronomer/issues#1643
Related https://github.com/astronomer/astro-ui/pull/745

### Astro UI

Tested in this order (success first then failure):

*Success Cases*
1. Get all the local testing services up and running: `docker compose up -d` 
2. Start Houston API
3. Start Astro UI
4. Create and Delete Deployments (Should work correctly with success message as usual)

*Failure Cases*
5. `docker container ls` and `docker container stop {NATS_CONTAINER}`
6. Create and Delete Deployment Should give a failure message and not add any changes to the database

The logs in Houston API should look something like this after stopping NATS:

```
2020-08-11T14:51:34 ERROR Disconnected from cluster houston using client houston-create-deployment-ae3988e2-651b-41ce-b258-581eda192535 and url nats://localhost:4222
2020-08-11T14:51:34 INFO Attempting to reconnect to cluster houston using client houston-create-deployment-ae3988e2-651b-41ce-b258-581eda192535 and url nats://localhost:4222
2020-08-11T14:51:34 ERROR Disconnected from cluster houston using client houston-delete-deployment-e6a2473d-2dc0-4b66-9c93-300c21d142c4 and url nats://localhost:4222
2020-08-11T14:51:34 INFO Attempting to reconnect to cluster houston using client houston-delete-deployment-e6a2473d-2dc0-4b66-9c93-300c21d142c4 and url nats://localhost:4222
2020-08-11T14:51:39 INFO Attempting to reconnect to cluster houston using client houston-create-deployment-ae3988e2-651b-41ce-b258-581eda192535 and url nats://localhost:4222
2020-08-11T14:51:39 INFO Attempting to reconnect to cluster houston using client houston-delete-deployment-e6a2473d-2dc0-4b66-9c93-300c21d142c4 and url nats://localhost:4222
```

### Astro CLI

```
$ ./astro deployment create nats-create-test --executor=k8s
Your Astro CLI Version (0.18.0) is ahead of the server version (0.15.1).
Consider downgrading your Astro CLI to match. See https://www.astronomer.io/docs/cli-quickstart for more information.
 NAME                 DEPLOYMENT NAME           ASTRO     DEPLOYMENT ID                 TAG
 nats-create-test     universal-galaxy-9790     0.0.0     ckdrn0ip2004m0848vxwvqqbv     %!s(MISSING)

 Successfully created deployment with Kubernetes executor. Deployment can be accessed at the following URLs

 Airflow Dashboard: https://deployments.local.astronomer.io/universal-galaxy-9790/airflow
$ ./astro deployment create nats-create-test-fail --executor=k8s
Your Astro CLI Version (0.18.0) is ahead of the server version (0.15.1).
Consider downgrading your Astro CLI to match. See https://www.astronomer.io/docs/cli-quickstart for more information.
Error: We are having problems with our system right now.  Please try again later.
$ ./astro deployment create nats-create-test-after-reconnect --executor=k8s
Your Astro CLI Version (0.18.0) is ahead of the server version (0.15.1).
Consider downgrading your Astro CLI to match. See https://www.astronomer.io/docs/cli-quickstart for more information.
 NAME                                 DEPLOYMENT NAME         ASTRO     DEPLOYMENT ID                 TAG
 nats-create-test-after-reconnect     astral-horizon-2686     0.0.0     ckdrn3e1q005208483djh0z3q     %!s(MISSING)

 Successfully created deployment with Kubernetes executor. Deployment can be accessed at the following URLs

 Airflow Dashboard: https://deployments.local.astronomer.io/astral-horizon-2686/airflow
```

## 📸 Screenshots

Screen Shot 2020-08-13 at 12 09 00 PM

 ~~Delete Deployment receives an error, but the client doesn't have the ability to display the error message yet~~:

*Update:* Delete deployment has an open PR to display the errors: https://github.com/astronomer/astro-ui/pull/745

Screen Shot 2020-08-13 at 12 08 44 PM

## 📋 Checklist

- [x] Rebased from the main (or release if patching) branch (before testing)
- [x] Ran `yarn lint && yarn test` before taking out of draft
- [x] Added/updated applicable tests
- [x] Tested against [Astro-UI](https://github.com/astronomer/astro-ui/) and [Astro-CLI](https://github.com/astronomer/astro-cli/) clients.
- [x] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/astro-docs/)

### CODE REVIEW

**Comment by adam2k** [comment]
@ryanahamilton I confirmed the toast for successful deletions, but when deleting a deployment fails there isn't any client side messaging.

We expect this to be rare and we will need some follow on work to alert the k8s healthz endpoint when things are down, so we can take some action.  For right now this seems like the bare minimum that we can do to handle the errors.

Is it possible to show the failure toast when deployments fail like it does for create deployment?

**Comment by adam2k** [comment]
@paolaperaza I'm fixing up some of the test here, but what is your opinion on the error message?  I can update it as I increase the test coverage.

`"We are having problems with our system right now.  Please try again later."`

It probably doesn't make sense in all contexts (enterprise and cloud), so something like:

`"We ran into a system problem.  Please try again later."`

**Comment by paolaperaza** [comment]
@adam2k Thanks for looping me in here, catching up real quick. Lemme make sure I understand what's goin on when these toast message show up before I give feedback:

- When exactly is this error showing? Is it when a user creates a deployment for the first time and that deployment isn't successfully created, or that's just an example of an existing error and we're talking about when a _deploy/code push_ fails?
- Not that we have to specify this, but will we have any sense of what exactly failed? (Whoops if this is rabbit hole question)
- Assuming it's when a deploy/code push fails, will we know the tag/docker image associated with that code push, or anything else about it? (User who pushed, if it was CLI/API, timestamp). Curious what we may be able to play with to show the user.
- The action item here is prob to direct the user to try again, aka deploy again? Can they do that immediately or is there some period of time they should wait?

**Comment by adam2k** [comment]
Thanks @paolaperaza!  Here are the answers in order:

>     * When exactly is this error showing? Is it when a user creates a deployment for the first time and that deployment isn't successfully created, or that's just an example of an existing error and we're talking about when a _deploy/code push_ fails?

This error displays when NATS Streaming is down.  In the future we can do this same kind of error handling for `commander` and `postgres` (I believe that doesn't exist for either right now).

>     * Not that we have to specify this, but will we have any sense of what exactly failed? (Whoops if this is rabbit hole question)

We could let them know that it's NATS Streaming?  I was trying to keep it general enough so it doesn't confuse them further.

>     * Assuming it's when a deploy/code push fails, will we know the tag/docker image associated with that code push, or anything else about it? (User who pushed, if it was CLI/API, timestamp). Curious what we may be able to play with to show the user.

We're checking for a NATS connection at the very beginning of each request and then making the DB requests and then checking and publishing to NATS again at the end of the request.  The failure can happen at either point. 

1.  If the error occurs at the beginning of the request there are no downstream consequences and the error is displayed to the client
2. On create deployment, for example, if only the second NATS request fails then we would have updated their deployment records in the database, but the worker will never pick up on this job and we'll have orphaned changes until their next set of changes are deployed.  From what I gather, this is the same edge case when Commander is down (we have a record of the deployment, but the system doesn't really deploy anything).

>     * The action item here is prob to direct the user to try again, aka deploy again? Can they do that immediately or is there some period of time they should wait?

It depends on how quickly NATS comes back up.  It could be a temporary issue or it could be something more significant.

- To add on to this we need an issue if one doesn't exist to improve our Kubernetes Houston API `healthz` endpoint so we're consistently checking that these system dependencies are up and running.  Including (Commander, Postgres, NATS Streaming and NATS).

**Comment by schnie** [comment]
Agree that the messaging should be generic and nothing related to NATS or any other tools that we use under the hood.

**Comment by ryanahamilton** [comment]
@adam2k will have a UI update shortly that can handle errors in addition to success.

**Comment by adam2k** [comment]
> @adam2k will have a UI update shortly that can handle errors in addition to success.

@ryanahamilton Thank you!  I can update the screens here and test with your PR.  Do you mind linking it when you're ready?

**Comment by paolaperaza** [comment]
@adam2k Word, thanks for that context. We just checked in via Slack, but to re-affirm you confirmed that this error is being shown when a user:

- Tries to create an Airflow Deployment via the Astro UI
- Tries to delete an Airflow Deployment via the Astro UI

I agree that we shouldn't expose any infra level jargon in there since it'll be shown to all end-users. We're thinking this for the copy of the message:

On delete:
> "Your Deployment could not be deleted due to a problem with the system. Please try again later or contact your administrator."

On create:
> "Your Deployment could not be created due to a problem with the system. Please try again later or contact your administrator."

Since this will be shown to Enterprise admins as well, it might be helpful to create a doc for Enterprise users that matches errors in the Astro UI to explanations of what's happening under-the-hood and suggestions on what to do to fix the problem. If I'm an Enterprise admin and I see that message, I think, "Ok I'm the system admin, what's wrong with the system and what do I need to do to get this thing to work?" Can create a GH issue on this is folks agree

**Comment by adam2k** [comment]
@paolaperaza thanks!  I updated the screenshots in the PR message.

**Comment by adam2k** [comment]
I'm not really sure what to do about that `lodash` issue.  We have a lot of libraries that are using lodash at various versions.  I can look into it further and try to address in a different branch.

**Comment by andriisoldatenko** [comment]
LGTM

**Pull request merged**
