### PR TITLE
Add namespace to update/upgrade release via commander request

### PR DESCRIPTION
**Pull request by andriisoldatenko**
fix https://github.com/astronomer/issues/issues/688
related PR https://github.com/astronomer/commander/pull/12

### CODE REVIEW

**Comment by ashb** [comment]
How was the namespace created/controlled before?

**Comment by ashb** [comment]
> fix astronomer/issues#688

This will make github close that issue automatically - is the the only change that is needed?

**Comment by andriisoldatenko** [comment]
@ashb in past (helm2) we using tiller and release was something helm store in system namespace close to tiller. Now we are using helm3 (without tiller) and helm3 3 store releases in same namespace in secrets:
https://github.com/astronomer/commander/pull/12/files#diff-1440e68d558b4bee95a174f33e0b3f04R125-R127
```
➜  cmd git:(helm3) ✗ k get secrets -n astronomer-geometrical-proton-2358NAME                                                           TYPE                                  DATA   AGE
default-token-4ftxx                                            kubernetes.io/service-account-token   3      7m34s
geometrical-proton-2358-airflow-metadata                       Opaque                                1      6m15s
geometrical-proton-2358-airflow-result-backend                 Opaque                                1      6m15s
geometrical-proton-2358-broker-url                             Opaque                                1      6m15s
geometrical-proton-2358-elasticsearch                          Opaque                                1      6m15s
geometrical-proton-2358-fernet-key                             Opaque                                1      6m15s
geometrical-proton-2358-pgbouncer-config                       Opaque                                2      6m15s
geometrical-proton-2358-pgbouncer-stats                        Opaque                                1      6m15s
geometrical-proton-2358-redis-password                         Opaque                                1      6m15s
geometrical-proton-2358-registry                               kubernetes.io/dockerconfigjson        1      6m15s
geometrical-proton-2358-scheduler-serviceaccount-token-z8rpb   kubernetes.io/service-account-token   3      6m15s
geometrical-proton-2358-worker-serviceaccount-token-8hwbj      kubernetes.io/service-account-token   3      6m15s
sh.helm.release.v1.geometrical-proton-2358.v1                  helm.sh/release.v1                    1      6m15s
```

**Comment by ashb** [comment]
Ahha, gotcha. Will this change fail without a matching change in commander? Does this mean we will _only_ work with helm3 going forward?

**Comment by andriisoldatenko** [comment]
@ashb i'll test right now.

**Comment by ashb** [comment]
@andriisoldatenko Where do we stand on this and the other Helm3 pr? (Are we supporting just helm3, or are we trying to support helm 2and3 concurrently)?

**Comment by andriisoldatenko** [comment]
@ashb @schnie this PR works well with v0.11 platform/commander
i can install deployments etc.
`kubectl get pods -n astronomer-telescopic-phases-2280`:

```
NAME                                                READY   STATUS    RESTARTS   AGE
telescopic-phases-2280-pgbouncer-7fc95d48b9-g57j2   2/2     Running   0          5m16s
telescopic-phases-2280-scheduler-65d96557d4-c5r2m   2/2     Running   0          5m16s
telescopic-phases-2280-statsd-865f7b8dd8-zcjkz      1/1     Running   0          5m16s
telescopic-phases-2280-webserver-75db5f8ff6-8pgnl   1/1     Running   0          5m16s
```

`k logs -f telescopic-phases-2280-webserver-75db5f8ff6-8pgnl -n astronomer-telescopic-phases-2280`:

```
10.244.0.1 - - [05/Feb/2020:16:53:47 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.15"
10.244.0.1 - - [05/Feb/2020:16:53:48 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.15"
[2020-02-05 16:53:50 +0000] [45] [INFO] Handling signal: ttin
[2020-02-05 16:53:50 +0000] [69] [INFO] Booting worker with pid: 69
[2020-02-05 16:53:50,891] {security.py:287} INFO - Loading Astronomer JWT signing cert from /etc/airflow/tls/tls.crt
[2020-02-05 16:53:50,994] {manager.py:703} WARNING - No user yet created, use flask fab command to do it.
[2020-02-05 16:53:51,879] {__init__.py:51} INFO - Using executor LocalExecutor
[2020-02-05 16:53:51,879] {dagbag.py:403} INFO - Filling up the DagBag from /usr/local/airflow/dags
10.244.0.1 - - [05/Feb/2020:16:53:52 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.15"
[2020-02-05 16:53:52,900] {security.py:461} INFO - Start syncing user roles.
[2020-02-05 16:53:53,278] {security.py:370} INFO - Fetching a set of all permission, view_menu from FAB meta-table
10.244.0.1 - - [05/Feb/2020:16:53:53 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.15"
[2020-02-05 16:53:53,664] {security.py:313} INFO - Cleaning faulty perms
[2020-02-05 16:53:54 +0000] [45] [INFO] Handling signal: ttou
[2020-02-05 16:53:54 +0000] [65] [INFO] Worker exiting (pid: 65)
10.244.0.1 - - [05/Feb/2020:16:53:57 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.15"
10.244.0.1 - - [05/Feb/2020:16:53:58 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.15"
10.244.0.1 - - [05/Feb/2020:16:54:02 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.15"
10.244.0.1 - - [05/Feb/2020:16:54:03 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.15"
10.244.0.1 - - [05/Feb/2020:16:54:07 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.15"
10.244.0.1 - - [05/Feb/2020:16:54:08 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.15"
10.244.0.1 - - [05/Feb/2020:16:54:12 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.15"
10.244.0.1 - - [05/Feb/2020:16:54:13 +0000] "GET /health HTTP/1.1" 200 187 "-" "kube-probe/1.15"
^C
```

**Pull request merged**
