### PR TITLE
bump alpine to 3.12 in ap-base

### PR DESCRIPTION
**Pull request by andriisoldatenko**

### CODE REVIEW

**Comment by schnie** [comment]
Looks like this isn't building right @andriisoldatenko

**Comment by andriisoldatenko** [comment]
@schnie correct, fixed in next commit, looks like there is no python2 🎉

**Comment by andriisoldatenko** [comment]
@schnie PTAL!

**Comment by andriisoldatenko** [comment]
@schnie can i merge now?

**Pull request merged**
