### PR TITLE
add kubectl

### PR DESCRIPTION
**Pull request by andriisoldatenko**
related PR https://github.com/astronomer/helm.astronomer.io/pull/264

### CODE REVIEW

**Comment by ashb** [comment]
What do we need this for?

**Comment by andriisoldatenko** [comment]
@ashb pls check related PR

**Comment by schnie** [comment]
LGTM, @ashb we need `kubectl` so we can run that quick command to check watch prisma status before running the job. Trying to avoid adding another image, at least while we have all these scans/rebuilds/refactorings going on.

It does kind of leak scope, which bothers me, but we avoid another image. What do you think?

**Comment by schnie** [comment]
Also, if we do merge this we'll need to update our prod image in astronomer/astronomer too (until we get our new pipelines).

**Pull request closed without merging**
