### PR TITLE
Remove local executor replica check

### PR DESCRIPTION
**Pull request by adam2k**
## Description

Allow users to select replicas for any executor type.

## 🎟 Issue(s)

Resolves astronomer/issues#2124
Depends on https://github.com/astronomer/astro-ui/pull/917

## 🧪 Functional Testing

1. Create a deployment and set the version to Airflow 2.0.0
2. Navigate to the LocalExecutor and change the scheduler replicas

## 📸 Screenshots

While using Astro UI branch: https://github.com/astronomer/astro-ui/pull/917

Screen Shot 2020-11-16 at 3 20 15 PM
Screen Shot 2020-11-16 at 3 20 47 PM
Screen Shot 2020-11-16 at 4 28 47 PM
Screen Shot 2020-11-16 at 4 29 05 PM
Screen Shot 2020-11-16 at 4 29 16 PM

## 📋 Checklist

- [x] Rebased from the main (or release if patching) branch (before testing)
- [x] Ran `yarn lint && yarn test` before taking out of draft
- [x] Added/updated applicable tests
- [x] Tested against [Astro-UI](https://github.com/astronomer/astro-ui/) and [Astro-CLI](https://github.com/astronomer/astro-cli/) clients.
- [ ] Communicated to/tagged owners of respective clients potentially impacted by these changes.
- [ ] Updated any related [documentation](https://github.com/astronomer/docs/)

### CODE REVIEW

**Review by andriisoldatenko — CHANGES_REQUESTED** [review]
```
```
/root/project/src/lib/deployments/config/index.unit.test.js
  37:3  error  'AIRFLOW_EXECUTOR_DEFAULT' is defined but never used  no-unused-vars
```
```

**Comment by adam2k** [comment]
> ```
> /root/project/src/lib/deployments/config/index.unit.test.js
>   37:3  error  'AIRFLOW_EXECUTOR_DEFAULT' is defined but never used  no-unused-vars
> ```

This is fixed.  It was a linting error.

**Comment by andriisoldatenko** [comment]
@adam2k we need some practical tests. 
code LGTM.

**Comment by adam2k** [comment]
> @adam2k we need some practical tests.
> code LGTM.

I dropped some screenshots in Astro UI: https://github.com/astronomer/astro-ui/pull/917  I can add them into this PR too.

**Comment by andriisoldatenko** [comment]
@adam2k yeah i saw it, it's for localExecutor. can you try also k8s/celery?

**Comment by adam2k** [comment]
> @adam2k yeah i saw it, it's for localExecutor. can you try also k8s/celery?

Sure, I added all three.

**Review by andriisoldatenko — APPROVED** [review]

**Pull request merged**
